/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto_venta;

import Ani_Panel.btn_color;
import java.awt.Color;
import javax.swing.UIDefaults;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Eduar
 */
public class Admin extends javax.swing.JFrame {
    public MigLayout layout;
    punto_venta.Accion_Mover Accion_mover = new Accion_Mover();
    btn_color AC = new btn_color();
    /*AC quiere decir animacion de color, se colocado la clase btn_color para animar al momento
    de hacer click*/
    public Admin() {
        initComponents();
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelRound2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_cerrar = new punto_venta.PanelRound();
        lbl_cerrar = new javax.swing.JLabel();
        btn_a = new punto_venta.PanelRound();
        lbl_a = new javax.swing.JLabel();
        btn_b = new punto_venta.PanelRound();
        lbl_b = new javax.swing.JLabel();
        btn_c = new punto_venta.PanelRound();
        lbl_c = new javax.swing.JLabel();
        btn_d = new punto_venta.PanelRound();
        lbl_d = new javax.swing.JLabel();
        Icon_logo = new javax.swing.JLabel();
        Panel_Card = new javax.swing.JPanel();
        Panel_a = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelRound1 = new punto_venta.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        Panel_b = new javax.swing.JPanel();
        Panel_c = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Panel_d = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(0, 0, 0));
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 20));

        btn_cerrar.setBackground(new java.awt.Color(51, 51, 51));
        btn_cerrar.setRoundBottomLeft(15);
        btn_cerrar.setRoundBottomRight(15);
        btn_cerrar.setRoundTopLeft(15);
        btn_cerrar.setRoundTopRight(15);
        btn_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cerrarMouseClicked(evt);
            }
        });
        btn_cerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cerrar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_cerrar.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lbl_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cerrar.setText("Salir");
        btn_cerrar.add(lbl_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 110, -1));

        panelRound2.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 130, 40));

        btn_a.setBackground(new java.awt.Color(0, 0, 0));
        btn_a.setForeground(new java.awt.Color(255, 255, 255));
        btn_a.setRoundBottomLeft(15);
        btn_a.setRoundBottomRight(15);
        btn_a.setRoundTopLeft(15);
        btn_a.setRoundTopRight(15);
        btn_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aMouseClicked(evt);
            }
        });
        btn_a.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_a.setBackground(new java.awt.Color(255, 255, 255));
        lbl_a.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lbl_a.setForeground(new java.awt.Color(255, 255, 255));
        lbl_a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        lbl_a.setText("Inventario");
        lbl_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_aMouseClicked(evt);
            }
        });
        btn_a.add(lbl_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, -1));

        panelRound2.add(btn_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 40));

        btn_b.setBackground(new java.awt.Color(0, 0, 0));
        btn_b.setRoundBottomLeft(15);
        btn_b.setRoundBottomRight(15);
        btn_b.setRoundTopLeft(15);
        btn_b.setRoundTopRight(15);
        btn_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bMouseClicked(evt);
            }
        });
        btn_b.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_b.setBackground(new java.awt.Color(255, 255, 255));
        lbl_b.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lbl_b.setForeground(new java.awt.Color(255, 255, 255));
        lbl_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        lbl_b.setText("Inventario");
        lbl_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_bMouseClicked(evt);
            }
        });
        btn_b.add(lbl_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, -1));

        panelRound2.add(btn_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 40));

        btn_c.setBackground(new java.awt.Color(0, 0, 0));
        btn_c.setRoundBottomLeft(15);
        btn_c.setRoundBottomRight(15);
        btn_c.setRoundTopLeft(15);
        btn_c.setRoundTopRight(15);
        btn_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cMouseClicked(evt);
            }
        });
        btn_c.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_c.setBackground(new java.awt.Color(255, 255, 255));
        lbl_c.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lbl_c.setForeground(new java.awt.Color(255, 255, 255));
        lbl_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        lbl_c.setText("Inventario");
        lbl_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cMouseClicked(evt);
            }
        });
        btn_c.add(lbl_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, -1));

        panelRound2.add(btn_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, 40));

        btn_d.setBackground(new java.awt.Color(0, 0, 0));
        btn_d.setRoundBottomLeft(15);
        btn_d.setRoundBottomRight(15);
        btn_d.setRoundTopLeft(15);
        btn_d.setRoundTopRight(15);
        btn_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dMouseClicked(evt);
            }
        });
        btn_d.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_d.setBackground(new java.awt.Color(255, 255, 255));
        lbl_d.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lbl_d.setForeground(new java.awt.Color(255, 255, 255));
        lbl_d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        lbl_d.setText("Inventario");
        lbl_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_dMouseClicked(evt);
            }
        });
        btn_d.add(lbl_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, -1));

        panelRound2.add(btn_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 140, 40));

        Icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo2.png"))); // NOI18N
        panelRound2.add(Icon_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 20, 201, 140));

        jPanel2.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 163, 640));

        Panel_Card.setLayout(new java.awt.CardLayout());

        Panel_a.setBackground(new java.awt.Color(0, 0, 0));
        Panel_a.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregar.setBackground(new java.awt.Color(255, 102, 102));
        btn_agregar.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Agregar producto");
        btn_agregar.setBorder(null);
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        Panel_a.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 310, 40));

        jComboBox2.setBackground(new java.awt.Color(51, 0, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(null);
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jComboBox2.setDoubleBuffered(true);
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        Panel_a.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 420, 30));

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTable2.setBackground(new java.awt.Color(0, 0, 0));
        jTable2.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "11", null, null, null},
                {null, "112", null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Cantidad", "Precio", "Eliminar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setFocusable(false);
        jTable2.setGridColor(new java.awt.Color(51, 255, 255));
        jTable2.setSelectionBackground(new java.awt.Color(153, 102, 255));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("ID");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("Producto");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Cantidad");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Precio");
            jTable2.getColumnModel().getColumn(4).setHeaderValue("Eliminar");
        }

        Panel_a.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 800, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo de inicio (1).png"))); // NOI18N
        Panel_a.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total a pagar = ");
        Panel_a.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, -1, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("$00.00");
        Panel_a.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 120, 30));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setBorder(null);
        Panel_a.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 130, 30));

        panelRound1.setBackground(new java.awt.Color(0, 51, 51));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pagar");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 50));

        Panel_a.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 140, 50));

        Panel_Card.add(Panel_a, "card3");

        Panel_b.setBackground(new java.awt.Color(51, 51, 51));
        Panel_b.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_Card.add(Panel_b, "card4");

        Panel_c.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Pagina C");

        javax.swing.GroupLayout Panel_cLayout = new javax.swing.GroupLayout(Panel_c);
        Panel_c.setLayout(Panel_cLayout);
        Panel_cLayout.setHorizontalGroup(
            Panel_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_cLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel3)
                .addContainerGap(537, Short.MAX_VALUE))
        );
        Panel_cLayout.setVerticalGroup(
            Panel_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_cLayout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(256, 256, 256))
        );

        Panel_Card.add(Panel_c, "card5");

        Panel_d.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Pagina D");

        javax.swing.GroupLayout Panel_dLayout = new javax.swing.GroupLayout(Panel_d);
        Panel_d.setLayout(Panel_dLayout);
        Panel_dLayout.setHorizontalGroup(
            Panel_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel4)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        Panel_dLayout.setVerticalGroup(
            Panel_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_dLayout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(256, 256, 256))
        );

        Panel_Card.add(Panel_d, "card2");

        jPanel2.add(Panel_Card, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 1050, 640));

        jMenu1.setText("File");

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        jMenu4.setText("jMenu4");
        jMenu1.add(jMenu4);

        jMenu5.setText("jMenu5");
        jMenu1.add(jMenu5);

        jMenu6.setText("jMenu6");
        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu7.setText("jMenu7");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarMouseClicked

    private void btn_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aMouseClicked
        AC.ani_colorA();
        Accion_mover.panel_hide(Panel_a, Panel_b, Panel_c, Panel_d);
        Panel_a.setVisible(true);
    }//GEN-LAST:event_btn_aMouseClicked

    private void btn_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bMouseClicked
        AC.ani_colorB();
        Accion_mover.panel_hide(Panel_a, Panel_b, Panel_c, Panel_d);
        Panel_b.setVisible(true);
    }//GEN-LAST:event_btn_bMouseClicked

    private void btn_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cMouseClicked
        AC.ani_colorC();
        Accion_mover.panel_hide(Panel_a, Panel_b, Panel_c, Panel_d);
        Panel_c.setVisible(true);
    }//GEN-LAST:event_btn_cMouseClicked

    private void btn_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dMouseClicked
        AC.ani_colorD();
        Accion_mover.panel_hide(Panel_a, Panel_b, Panel_c, Panel_d);
        Panel_d.setVisible(true);
    }//GEN-LAST:event_btn_dMouseClicked

    private void lbl_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aMouseClicked
        AC.ani_colorA();
        Accion_mover.panel_hide(Panel_a, Panel_b, Panel_c, Panel_d);
        Panel_a.setVisible(true);
    }//GEN-LAST:event_lbl_aMouseClicked

    private void lbl_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bMouseClicked
        AC.ani_colorB();
        Accion_mover.panel_hide(Panel_a, Panel_b, Panel_c, Panel_d);
        Panel_b.setVisible(true);
    }//GEN-LAST:event_lbl_bMouseClicked

    private void lbl_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cMouseClicked
        AC.ani_colorC();
        Accion_mover.panel_hide(Panel_a, Panel_b, Panel_c, Panel_d);
        Panel_c.setVisible(true);
    }//GEN-LAST:event_lbl_cMouseClicked

    private void lbl_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dMouseClicked
        AC.ani_colorD();
        Accion_mover.panel_hide(Panel_a, Panel_b, Panel_c, Panel_d);
        Panel_d.setVisible(true);
    }//GEN-LAST:event_lbl_dMouseClicked

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
       
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
       
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        jComboBox2.setSelectedItem(Color.BLACK);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon_logo;
    private javax.swing.JPanel Panel_Card;
    private javax.swing.JPanel Panel_a;
    private javax.swing.JPanel Panel_b;
    private javax.swing.JPanel Panel_c;
    private javax.swing.JPanel Panel_d;
    public static punto_venta.PanelRound btn_a;
    public static javax.swing.JButton btn_agregar;
    public static punto_venta.PanelRound btn_b;
    public static punto_venta.PanelRound btn_c;
    private punto_venta.PanelRound btn_cerrar;
    public static punto_venta.PanelRound btn_d;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    public static javax.swing.JLabel lbl_a;
    public static javax.swing.JLabel lbl_b;
    public static javax.swing.JLabel lbl_c;
    private javax.swing.JLabel lbl_cerrar;
    public static javax.swing.JLabel lbl_d;
    private punto_venta.PanelRound panelRound1;
    private javax.swing.JPanel panelRound2;
    // End of variables declaration//GEN-END:variables

}
